services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    build:
      context: .
      dockerfile: Dockerfile.localstack
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=1
      - PERSISTENCE=1
      - AWS_DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_DOCKER_NETWORK=local-ml-flow_default
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_REMOTE_DOCKER=0
      - LAMBDA_LIMITS_CREATE_FUNCTION_REQUEST_SIZE=256000000
      - LAMBDA_LIMITS_CREATE_FUNCTION_REQUEST_SIZE=256000000
      - LAMBDA_LIMITS_CODE_SIZE_ZIPPED=256000000
      - LAMBDA_LIMITS_CODE_SIZE_UNZIPPED=512000000
    volumes:
      - "./localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./src/config/housing.csv:/tmp/data/housing.csv"
      - "./bin/init:/etc/localstack/init/ready.d"
      - "./terraform:/opt/code/terraform"