name: main pipeline

on:
  push:
    branches: [ "main", "develop", "feature/**", "fix/**", "release/**" ]
  pull_request:
    branches: [ "main", "develop", "feature/**", "fix/**", "release/**" ]

jobs:
  sonar-task:
    uses: ./.github/workflows/sonar.yml
    secrets: inherit

  build-task:
    needs: [sonar-task]
    uses: ./.github/workflows/build.yml
    secrets: inherit

  promote-task:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build-task
    uses: ./.github/workflows/promote.yml
    secrets: inherit